project:
  type: website
  execute-dir: project
  output-dir: docs

website:
  title: "R Programming for Biologists"
  navbar:
    left:
      - text: "Home"
        href: index.qmd

execute:
  freeze: auto

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



