project:
  type: website
  execute-dir: project
  output-dir: docs

website:
  title: "R Programming for Biologists"
  favicon: materials/images/logo_lyon.png
  repo-url: https://github.com/njlyon0/teach_r-for-bio
  repo-actions: [issue]
  navbar:
    right:
      - text: "Alumni"
        href: alumni.qmd
      - text: "Instructors"
        menu:
          - text: "Nick J Lyon"
            href: https://njlyon0.github.io/
      - icon: github
        href: https://github.com/njlyon0/teach_r-for-bio
        aria-label: GitHub
  sidebar:
    style: "docked"
    alignment: left
    border: true
    collapse-level: 2
    contents:
      - section: "Course Overview"
        contents:
          - text: "Syllabus"
            href: index.qmd
          - text: "Example Data"
            href: data.qmd
          - text: "Readings"
            href: readings.qmd
          - text: "Answer Keys"
            href: keys.qmd
      - section: "Assignment Rubrics"
        contents:
          - text: "Muddiest Point"
            href: rubrics/rubric_muddiest-point.qmd
          - text: "Homework"
            href: rubrics/rubric_homework.qmd
          - text: "GitHub Presence"
            href: rubrics/rubric_github.qmd
          - text: "Function Tutorials"
            href: rubrics/rubric_tutorials.qmd
      - section: "Course Content"
        contents:
          - text: "Week 1 Content"
            href: materials/home_week1.qmd
          - text: "Week 2 Content"
            href: materials/home_week2.qmd
          - text: "Week 3 Content"
            href: materials/home_week3.qmd
          - text: "Week 4 Content"
            href: materials/home_week4.qmd
          - text: "Week 5 Content"
            href: materials/home_week5.qmd
          - text: "Week 6 Content"
            href: materials/home_week6.qmd
          - text: "Week 7 Content"
            href: materials/home_week7.qmd
          - text: "Week 8 Content"
            href: materials/home_week8.qmd
  page-footer:
    center: "Copyright 2024, Nicholas J Lyon"

execute:
  freeze: auto

format:
  html:
    code-overflow: wrap
    code-line-numbers: false
    code-copy: hover
    theme:
      light: lyonlight.scss
      dark: lyondark.scss
    mainfont: Open Sans
    toc: true
    link-external-newwindow: true
    link-external-icon: false
