project:
  type: website
  execute-dir: project
  output-dir: docs

website:
  title: "R Programming for Biologists"
  repo-url: https://github.com/njlyon0/teach_r-for-bio
  repo-actions: [issue]
  navbar:
    background: primary
    left:
      - text: "Course Home"
        href: index.qmd
    right: 
      - text: "Instructors"
        menu:
          - text: "Nick J Lyon"
            href: https://njlyon0.github.io/
  page-footer: 
    center: "Copyright 2024, Nicholas J Lyon"
    background: secondary

execute:
  freeze: auto

format:
  html:
    theme: 
      light: lyonlight.scss
      dark: lyondark.scss
    mainfont: Open Sans
    toc: true
    link-external-newwindow: true
    link-external-icon: false
